name: Build & Release

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      frp:
        type: boolean
        default: false
      xray-core:
        type: boolean
        default: false
      rclone:
        type: boolean
        default: false
      restic:
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Build all (single script)
        env:
          FORCE_UPDATE_FRP: ${{ inputs.frp }}
          FORCE_UPDATE_XRAY_CORE: ${{ inputs.xray-core }}
          FORCE_UPDATE_RCLONE: ${{ inputs.rclone }}
          FORCE_UPDATE_RESTIC: ${{ inputs.restic }}
        run: |
          bash build.sh

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0
          files: |
            /tmp/build-script/dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
